version: "3.3"
services:
  app:
    image: axelpal/code-review-tool-app:${IMAGE_TAG:-local}
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    entrypoint: /wait-for postgres:5432 -t 60 -- /app-entrypoint.sh
    command: php-fpm -F
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: "serverName=code-review-tool"
      STARTUP_START_SUPERVISORD: "true"
      STARTUP_START_CONSUMERS: "true"
      STARTUP_START_CRON: "true"
      DEFAULT_WORKERS_COUNT: 2
    networks:
      app_net:
    volumes:
      - .:/app:delegated
      - ./docker/php/app-entrypoint.sh:/app-entrypoint.sh
      - phpstan_data:/tmp/phpstan:delegated

  nginx:
    image: axelpal/code-review-tool-nginx:${IMAGE_TAG:-local}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        APP_IMAGE: axelpal/code-review-tool-app:${IMAGE_TAG:-local}
    tty: true
    networks:
      app_net:

    volumes:
      - ./public:/app/public:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/includes:/etc/nginx/includes
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  redis:
    image: redis
    tty: true
    profiles:
      - db
    volumes:
      - redis_data:/data:delegated
    networks:
      app_net:
  postgres:
    image: postgres:13-alpine
    tty: true
    profiles:
      - db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      app_net:
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated

volumes:
  postgres_data:
  redis_data:
  phpstan_data:

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
