name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            axelpal/code-review-tag-tool-app
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/php/Dockerfile
          platforms: "linux/amd64,linux/arm64/v8,linux/arm/v7"
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Unit tests
        uses: addnab/docker-run-action@v3
        with:
          image: axelpal/code-review-tag-tool-app:${{ env.GITHUB_REF_SLUG }}
          run: |
            cp .env.testing .env
            ./artisan config:cache --env=testing
            ./artisan test
            ./artisan config:cache
      - name: Static analysis
        uses: addnab/docker-run-action@v3
        with:
          image: axelpal/code-review-tag-tool-app:${{ env.GITHUB_REF_SLUG }}
          run: ./vendor/bin/phpstan analyse .

  build-nginx:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            axelpal/code-review-tag-tool-nginx
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -
        name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/nginx/Dockerfile
          platforms: "linux/amd64,linux/arm64/v8,linux/arm/v7"
          build-args: |
            APP_IMAGE=axelpal/code-review-tag-tool-app:${{ env.GITHUB_REF_SLUG }}